### ISSUE TITLE
Execute stop record soon after start

### ISSUE THREAD

**Issue by lizhuoyuan** [llfbandit/record#114]
D/Record - MR( 1852): Start recording
D/Record - MR( 1852): Stop recording
E/MediaRecorder( 1852): stop failed: -1007
E/MethodChannel#com.llfbandit.record( 1852): Failed to handle method call
E/MethodChannel#com.llfbandit.record( 1852): java.lang.RuntimeException: stop failed.
E/MethodChannel#com.llfbandit.record( 1852): 	at android.media.MediaRecorder.stop(Native Method)
E/MethodChannel#com.llfbandit.record( 1852): 	at com.llfbandit.record.MediaRecorder.stopRecording(MediaRecorder.java:137)
E/MethodChannel#com.llfbandit.record( 1852): 	at com.llfbandit.record.MediaRecorder.stop(MediaRecorder.java:69)
E/MethodChannel#com.llfbandit.record( 1852): 	at com.llfbandit.record.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:60)
E/MethodChannel#com.llfbandit.record( 1852): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#com.llfbandit.record( 1852): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:178)
E/MethodChannel#com.llfbandit.record( 1852): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0$DartMessenger(DartMessenger.java:206)
E/MethodChannel#com.llfbandit.record( 1852): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$R4HPk6oFVb-i-YR_PN9YE6kqx1I.run(Unknown Source:12)
E/MethodChannel#com.llfbandit.record( 1852): 	at android.os.Handler.handleCallback(Handler.java:883)
E/MethodChannel#com.llfbandit.record( 1852): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/MethodChannel#com.llfbandit.record( 1852): 	at android.os.Looper.loop(Looper.java:230)
E/MethodChannel#com.llfbandit.record( 1852): 	at android.app.ActivityThread.main(ActivityThread.java:8062)
E/MethodChannel#com.llfbandit.record( 1852): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#com.llfbandit.record( 1852): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
E/MethodChannel#com.llfbandit.record( 1852): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
I/flutter ( 1852): 停止录制语音:PlatformException(error, stop failed., null, java.lang.RuntimeException: stop failed.
I/flutter ( 1852): 	at android.media.MediaRecorder.stop(Native Method)
I/flutter ( 1852): 	at com.llfbandit.record.MediaRecorder.stopRecording(MediaRecorder.java:137)
I/flutter ( 1852): 	at com.llfbandit.record.MediaRecorder.stop(MediaRecorder.java:69)
I/flutter ( 1852): 	at com.llfbandit.record.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:60)
I/flutter ( 1852): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
I/flutter ( 1852): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:178)
I/flutter ( 1852): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0$DartMessenger(DartMessenger.java:206)
I/flutter ( 1852): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$R4HPk6oFVb-i-YR_PN9YE6kqx1I.run(Unknown Source:12)
I/flutter ( 1852): 	at android.os.Handler.handleCallback(Handler.java:883)
I/flutter ( 1852): 	at android.os.Handler.dispatchMessage(Handler.java:100)
I/flutter ( 1852): 	at android.os.Looper.loop(Looper.java:230)
I/flutter ( 1852): 	at android.app.ActivityThread.main(ActivityThread

**Comment by llfbandit** [comment]
Thanks for report.
I made an attempt to not report this exception on version 4.4.3.
I can't do more since MediaRecorder does not handle itself its state.

**Comment by lizhuoyuan** [comment]
Is the stop called because the recording has not started? 
Can you judge whether it can be stopped when it is stopped?
Maybe the stop recording method itself needs to judge more conditions before executing it backwards
