### ISSUE TITLE
It was not working on macOS 13.3

### ISSUE THREAD

**Issue by wuynng** [llfbandit/record#177]
**Package version**
4.4.4

**Describe the bug**
It was not working on my macbook:
```
Launching lib/main.dart on macOS in debug mode...
CocoaPods' output:
↳
      Preparing
    Analyzing dependencies
    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
    Finding Podfile changes
      A flutter_desktop_audio_recorder
      A path_provider_foundation
      A record_macos
      - FlutterMacOS
      - sqflite
      - url_launcher_macos
    Fetching external sources
    -> Fetching podspec for `FlutterMacOS` from `Flutter/ephemeral`
    -> Fetching podspec for `flutter_desktop_audio_recorder` from `Flutter/ephemeral/.symlinks/plugins/flutter_desktop_audio_recorder/macos`
    -> Fetching podspec for `path_provider_foundation` from `Flutter/ephemeral/.symlinks/plugins/path_provider_foundation/darwin`
    -> Fetching podspec for `record_macos` from `Flutter/ephemeral/.symlinks/plugins/record_macos/macos`
    -> Fetching podspec for `sqflite` from `Flutter/ephemeral/.symlinks/plugins/sqflite/macos`
    -> Fetching podspec for `url_launcher_macos` from `Flutter/ephemeral/.symlinks/plugins/url_launcher_macos/macos`
    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_c_0_4.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/c/0/4/Flutter/3.0.0/Flutter.podspec.json exists! Returning local because checking is only performed in repo update
    [!] CocoaPods could not find compatible versions for pod "record_macos":
      In Podfile:
        record_macos (from `Flutter/ephemeral/.symlinks/plugins/record_macos/macos`)
    Specs satisfying the `record_macos (from `Flutter/ephemeral/.symlinks/plugins/record_macos/macos`)` dependency were found, but they required a higher minimum deployment target.
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:317:in `raise_error_unless_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:299:in `block in unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `tap'
...
Exception: Error running pod install
Exited
```

**To Reproduce**
1. git clone https://github.com/llfbandit/record.git
2. use vscode to open `example` directory
3. press **F5** to run example

**Desktop:**
 - OS: macOS 
 - Version 13.3

**Comment by llfbandit** [comment]
`Specs satisfying the `record_macos (from `Flutter/ephemeral/.symlinks/plugins/record_macos/macos`)` dependency were found, but they required a higher minimum deployment target.`
