### ISSUE TITLE
WEB: Exception on starting recording in chrome 

### ISSUE THREAD

**Issue by Abhijit-Revamp** [llfbandit/record#290]
**Package version**: 5.0.4

**Environment**
 - OS: macOS
 - Browser Chrome

**Describe the bug**
When starting recording with STREAM Chrome is throwing error in console
When stopping getting error in console and return path is NULL

RecordConfig(AudioEncoder.pcm16bits)

**To Reproduce**

Steps to reproduce the behaviour:
1. Start Recording 
```
    if (await _audioRecorder.hasPermission()) {
      // // Start recording to file
      // await record.start(const RecordConfig(), path: 'aFullPath/myFile.m4a');
      await _audioRecorder
          .startStream(const RecordConfig(encoder: AudioEncoder.pcm16bits));
    }

```
2. See error
```
[Error] Error from backend:

Error: Bad state: Not connected to an application.

Stack Trace:
#0      DevHandler._handleConnection.<anonymous closure> (package:dwds/src/handlers/dev_handler.dart:272:13)
#1      _rootRunUnary (dart:async/zone.dart:1407:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#6      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
#7      _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
#8      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
#9      _rootRunUnary (dart:async/zone.dart:1415:13)
#10     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#14     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#15     _StreamController._add (dart:async/stream_controller.dart:658:7)
#16     _StreamController.add (dart:async/stream_controller.dart:606:5)
#17     new WebSocketImpl.fromSocket.<anonymous closure> (package:web_socket_channel/src/copy/web_socket_impl.dart:730:21)
#18     _rootRunUnary (dart:async/zone.dart:1407:47)
#19     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#22     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#23     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#24     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#25     _WebSocketProtocolTransformer._messageFrameEnd (package:web_socket_channel/src/copy/web_socket_impl.dart:319:23)
#26     _WebSocketProtocolTransformer.add (package:web_socket_channel/src/copy/web_socket_impl.dart:218:46)
#27     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#28     _rootRunUnary (dart:async/zone.dart:1407:47)
#29     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#30     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#33     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#34     _StreamController._add (dart:async/stream_controller.dart:658:7)
#35     _StreamController.add (dart:async/stream_controller.dart:606:5)
#36     _Socket._onData (dart:io-patch/socket_patch.dart:2449:41)
#37     _rootRunUnary (dart:async/zone.dart:1415:13)
#38     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#39     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#42     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#43     _StreamController._add (dart:async/stream_controller.dart:658:7)
#44     _StreamController.add (dart:async/stream_controller.dart:606:5)
#45     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1936:33)
#46     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1379:14)
#47     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#48     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#49     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#50     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)

	(anonymous function) (client.js:26092)
	(anonymous function) (client.js:4049)
	call$2 (client.js:12422)
	_asyncStartSync (client.js:4013)
	$call$body$main__closure (client.js:26100)
	call$1 (client.js:26013)
	_rootRunUnary (client.js:4431)
	runUnary$2$2 (client.js:13817)
	runUnaryGuarded$1$2 (client.js:13764)
	_sendData$1 (client.js:13357)
	_add$1 (client.js:13303)
	_add$1 (client.js:13638)
	_handleData$2 (client.js:13701)
	_handleData$1 (client.js:13664)
	(anonymous function) (client.js:1741)
	_rootRunUnary (client.js:4431)
	runUnary$2$2 (client.js:13817)
	runUnaryGuarded$1$2 (client.js:13764)
	_sendData$1 (client.js:13357)
	_add$1 (client.js:13303)
	_sendData$1 (client.js:13149)
	add$1 (client.js:13028)
	(anonymous function) (client.js:1799)
	_rootRunUnary (client.js:4431)
	runUnary$2$2 (client.js:13817)
	runUnaryGuarded$1$2 (client.js:13764)
	_sendData$1 (client.js:13357)
	_add$1 (client.js:13303)
	_sendData$1 (client.js:13149)
	add$1 (client.js:13028)
	add$1 (client.js:25366)
	_innerListen$1 (client.js:25698)
	(anonymous function) (client.js:1741)
	call$1 (client.js:25644)
	_rootRunUnary (client.js:4435)
	runUnary$2$2 (client.js:13817)
	runUnaryGuarded$1$2 (client.js:13764)
	call$1 (client.js:13954)
	Primitives_applyFunction (client.js:1304)
	Function_apply (client.js:5963)
	_callDartFunctionFast (client.js:8360)
	(anonymous function) (client.js:8351)
```

**Expected behavior**

Audio to be recorded as stream

**Comment by llfbandit** [comment]
Do you subscribe to the returned stream?

**Comment by Abhijit-Revamp** [comment]
@llfbandit 
I used the available documentation / samples 
Can you please refer me to correct documentaton?

**Comment by llfbandit** [comment]
Have a look to the example.
The stacktrace refers to a problem with your debugging session. There's anything related to this package.
