### ISSUE TITLE
dispose record while on pause state cause exception stop failed -1007

### ISSUE THREAD

**Issue by duongtruong12** [llfbandit/record#30]
Hi Developer
I have faced an issue about dispose while on pause state of record

Here is my code

Here is the log
`D/Record  ( 8419): Start recording
D/Record  ( 8419): Pause recording
D/Record  ( 8419): Stop recording
E/MediaRecorder( 8419): stop failed: -1007
E/MethodChannel#com.llfbandit.record( 8419): Failed to handle method call
E/MethodChannel#com.llfbandit.record( 8419): java.lang.RuntimeException: stop failed.
E/MethodChannel#com.llfbandit.record( 8419): 	at android.media.MediaRecorder.stop(Native Method)
E/MethodChannel#com.llfbandit.record( 8419): 	at com.llfbandit.record.Recorder.stopRecording(Recorder.java:115)
E/MethodChannel#com.llfbandit.record( 8419): 	at com.llfbandit.record.Recorder.stop(Recorder.java:63)
E/MethodChannel#com.llfbandit.record( 8419): 	at com.llfbandit.record.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:62)
E/MethodChannel#com.llfbandit.record( 8419): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#com.llfbandit.record( 8419): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/MethodChannel#com.llfbandit.record( 8419): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/MethodChannel#com.llfbandit.record( 8419): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#com.llfbandit.record( 8419): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#com.llfbandit.record( 8419): 	at android.os.Looper.loop(Looper.java:183)
E/MethodChannel#com.llfbandit.record( 8419): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/MethodChannel#com.llfbandit.record( 8419): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#com.llfbandit.record( 8419): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/MethodChannel#com.llfbandit.record( 8419): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter ( 8419): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, stop failed., null, java.lang.RuntimeException: stop failed.
E/flutter ( 8419): 	at android.media.MediaRecorder.stop(Native Method)
E/flutter ( 8419): 	at com.llfbandit.record.Recorder.stopRecording(Recorder.java:115)
E/flutter ( 8419): 	at com.llfbandit.record.Recorder.stop(Recorder.java:63)
E/flutter ( 8419): 	at com.llfbandit.record.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:62)
E/flutter ( 8419): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter ( 8419): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/flutter ( 8419): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/flutter ( 8419): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 8419): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter ( 8419): 	at android.os.Looper.loop(Looper.java:183)
E/flutter ( 8419): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/flutter ( 8419): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 8419): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/flutter ( 8419): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter ( 8419): )
E/flutter ( 8419): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter ( 8419): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter ( 8419): <asynchronous suspension>
E/flutter ( 8419): #2      _RepeatState._disposeAudio (package:baby_talk/screen/home/repeat/repeat_screen.dart:56:5)
E/flutter ( 8419): <asynchronous suspension>
E/flutter ( 8419): 
`

**Comment by duongtruong12** [comment]
i have found the problem, i have start() a record and pause() it immediately after start() was called, afterr that i have stop() or dispose() it will throw exception

**Comment by llfbandit** [comment]
Do you wait for those calls ?
Please, provide a reproducer.

**Comment by electrooz** [comment]
I have this same issue, only mine happens when timer stops it (not me).
```
PlatformException (PlatformException(error, stop failed., null, java.lang.RuntimeException: stop failed.
	at android.media.MediaRecorder.stop(Native Method)
	at com.llfbandit.record.Recorder.stopRecording(Recorder.java:115)
	at com.llfbandit.record.Recorder.stop(Recorder.java:63)
	at com.llfbandit.record.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:62)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(lambda)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5765)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
))``` That's the output.

This is my code. Mostly kept the example just added my timers to make it start/stop recording at a specified time.

```dart
import 'package:flutter/material.dart';
import 'dart:io' as io;
import 'dart:async';

import 'package:path_provider/path_provider.dart';
import 'package:record/record.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Audio Recorder Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        brightness: Brightness.dark,
      ),
      home: const MyHomePage(),
    );
  }
}

DateTime startTime = DateTime(2022, 02, 25, 17, 18, 00);
DateTime endTime = DateTime(2022, 02, 25, 17, 20, 00);

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool showPlayer = false;

  @override
  void initState() {
    showPlayer = false;
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: AudioRecorder(),
        ),
      ),
    );
  }
}

class AudioRecorder extends StatefulWidget {
  const AudioRecorder({Key? key}) : super(key: key);

  @override
  _AudioRecorderState createState() => _AudioRecorderState();
}

class _AudioRecorderState extends State<AudioRecorder> {
  bool _isRecording = false;
  bool _isPaused = false;
  int _recordDuration = 0;
  Timer? _timer;
  Timer? _ampTimer;
  final _audioRecorder = Record();
  Amplitude? _amplitude;

  @override
  void initState() {
    _isRecording = false;
    super.initState();
  }

  @override
  void dispose() {
    _timer?.cancel();
    _ampTimer?.cancel();
    _audioRecorder.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (_isRecording == false) {
      Timer(startTime.difference(DateTime.now()), () {
        _start();
        print('START RECORDING');
      });
    }

    if (_isRecording) {
      Timer(endTime.difference(DateTime.now()), () {
        _stop();
        print('END RECORDING');
      });
    }

    return MaterialApp(
      home: Scaffold(
        body: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const SizedBox(
              height: 20,
            ),
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                _buildRecordStopControl(),
                const SizedBox(width: 20),
                _buildPauseResumeControl(),
                const SizedBox(width: 20),
                _buildText(),
              ],
            ),
            if (_amplitude != null) ...[
              const SizedBox(height: 40),
              Text('Current: ${_amplitude?.current ?? 0.0}'),
              Text('Max: ${_amplitude?.max ?? 0.0}'),
            ],
          ],
        ),
      ),
    );
  }

  Widget _buildRecordStopControl() {
    late Icon icon;
    late Color color;

    if (_isRecording || _isPaused) {
      icon = const Icon(Icons.stop, color: Colors.red, size: 30);
      color = Colors.red.withOpacity(0.1);
    } else {
      final theme = Theme.of(context);
      icon = Icon(Icons.mic, color: theme.primaryColor, size: 30);
      color = theme.primaryColor.withOpacity(0.1);
    }

    return ClipOval(
      child: Material(
        color: color,
        child: InkWell(
          child: SizedBox(width: 56, height: 56, child: icon),
          onTap: () {
            _isRecording ? _stop() : _start();
          },
        ),
      ),
    );
  }

  Widget _buildPauseResumeControl() {
    if (!_isRecording && !_isPaused) {
      return const SizedBox.shrink();
    }

    late Icon icon;
    late Color color;

    if (!_isPaused) {
      icon = const Icon(Icons.pause, color: Colors.red, size: 30);
      color = Colors.red.withOpacity(0.1);
    } else {
      final theme = Theme.of(context);
      icon = const Icon(Icons.play_arrow, color: Colors.red, size: 30);
      color = theme.primaryColor.withOpacity(0.1);
    }

    return ClipOval(
      child: Material(
        color: color,
        child: InkWell(
          child: SizedBox(width: 56, height: 56, child: icon),
          onTap: () {
            _isPaused ? _resume() : _pause();
          },
        ),
      ),
    );
  }

  Widget _buildText() {
    if (_isRecording || _isPaused) {
      return _buildTimer();
    }

    return Text("Waiting to record");
  }

  Widget _buildTimer() {
    final String minutes = _formatNumber(_recordDuration ~/ 60);
    final String seconds = _formatNumber(_recordDuration % 60);

    return Text(
      '$minutes : $seconds',
      style: TextStyle(color: Colors.red),
    );
  }

  String _formatNumber(int number) {
    String numberStr = number.toString();
    if (number < 10) {
      numberStr = '0' + numberStr;
    }

    return numberStr;
  }

  Future<void> _start() async {
    try {
      if (await _audioRecorder.hasPermission()) {
        await _audioRecorder.start();

        bool isRecording = await _audioRecorder.isRecording();
        setState(() {
          _isRecording = isRecording;
          _recordDuration = 0;
        });

        _startTimer();
      }
    } catch (e) {
      print(e);
    }
  }

  Future<void> _stop() async {
    _timer?.cancel();
    _ampTimer?.cancel();
    final path = await _audioRecorder.stop();
    // doesn't pass this ^
    setState(() => _isRecording = false);
  }

  Future<void> _pause() async {
    _timer?.cancel();
    _ampTimer?.cancel();
    await _audioRecorder.pause();

    setState(() => _isPaused = true);
  }

  Future<void> _resume() async {
    _startTimer();
    await _audioRecorder.resume();

    setState(() => _isPaused = false);
  }

  void _startTimer() {
    _timer?.cancel();
    _ampTimer?.cancel();

    _timer = Timer.periodic(const Duration(seconds: 1), (Timer t) {
      setState(() => _recordDuration++);
    });

    _ampTimer =
        Timer.periodic(const Duration(milliseconds: 200), (Timer t) async {
      _amplitude = await _audioRecorder.getAmplitude();
      setState(() {});
    });
  }
}
```
