### ISSUE TITLE
java.lang.IllegalArgumentException: Can only use lower 16 bits for requestCode

### ISSUE THREAD

**Issue by vipCodeError** [llfbandit/record#36]
No Idea What went wrong .

  Future<void> _start() async {
    try {
      if (await _audioRecorder.hasPermission()) {
        await _audioRecorder.start(encoder: AudioEncoder.AAC);

        bool isRecording = await _audioRecorder.isRecording();
        setState(() {
          _isRecording = isRecording;
          _recordDuration = 0;
        });

        _startTimer();
      }
    } catch (e) {
      print(e);
    }
  }

```
E/MethodChannel#com.llfbandit.record(20547): java.lang.IllegalArgumentException: Can only use lower 16 bits for requestCode
E/MethodChannel#com.llfbandit.record(20547): 	at androidx.fragment.app.FragmentActivity.checkForValidRequestCode(FragmentActivity.java:715)
E/MethodChannel#com.llfbandit.record(20547): 	at androidx.fragment.app.FragmentActivity.validateRequestPermissionsRequestCode(FragmentActivity.java:730)
E/MethodChannel#com.llfbandit.record(20547): 	at androidx.core.app.ActivityCompat.requestPermissions(ActivityCompat.java:500)
E/MethodChannel#com.llfbandit.record(20547): 	at com.llfbandit.record.MethodCallHandlerImpl.askForPermission(MethodCallHandlerImpl.java:132)
E/MethodChannel#com.llfbandit.record(20547): 	at com.llfbandit.record.MethodCallHandlerImpl.hasPermission(MethodCallHandlerImpl.java:120)
E/MethodChannel#com.llfbandit.record(20547): 	at com.llfbandit.record.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:81)
E/MethodChannel#com.llfbandit.record(20547): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#com.llfbandit.record(20547): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#com.llfbandit.record(20547): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#com.llfbandit.record(20547): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#com.llfbandit.record(20547): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#com.llfbandit.record(20547): 	at android.os.Looper.loop(Looper.java:197)
E/MethodChannel#com.llfbandit.record(20547): 	at android.app.ActivityThread.main(ActivityThread.java:7807)
E/MethodChannel#com.llfbandit.record(20547): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#com.llfbandit.record(20547): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#com.llfbandit.record(20547): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
```

**Comment by LucasMdosAnjos** [comment]
I think this package is abandoned because i asked if this library can have support for desktop and got no answer until now.

**Comment by llfbandit** [comment]
Thanks for the report.
The permission code is generated from hash code on Android.
I will freeze it in an upcoming version.

**Comment by JeromeGsq** [comment]
Hi, any news about this issue @llfbandit ?
Thanks

**Comment by llfbandit** [comment]
Sorry for the late change. Version 3.0.1 is now uploaded to fix this issue.

**Comment by JeromeGsq** [comment]
@llfbandit 
Thank you for the quick answer. 
I have an issue with this version 3.0.1 after a `flutter pub get`. Can you help me?

```
Because every version of record_web depends on record_platform_interface ^0.1.0 and record >=3.0.1 depends on record_platform_interface ^0.2.0, record_web is incompatible with record >=3.0.1.
So, because project depends on record ^3.0.1 which depends on record_web ^0.2.0, version solving failed.
Running "flutter pub get" in project...                                    
pub get failed (1; So, because project depends on record ^3.0.1 which depends on record_web ^0.2.0, version solving failed.)
```

**Comment by llfbandit** [comment]
Yes that's true. I did not save correctly the pubspec file on web package...
Version 3.0.2 on the run... :(

**Comment by llfbandit** [comment]
Done, please confirm the fix.

**Comment by JeromeGsq** [comment]
It's OK! Thank you very much

**Comment by llfbandit** [comment]
You're welcome. Thanks for the feedback. No time to spend on my personal projects since too long...
