### ISSUE TITLE
Android app is constantly crashing when starting recording

### ISSUE THREAD

**Issue by gonuit** [llfbandit/record#386]
**Package version**
- record: 5.1.2
- record_android: 1.2.5

**Environment**
 - OS: Android

**Describe the bug**

App is crashing as soon as start method is invoked.

```dart
await _recorder.start(
  const RecordConfig(
    encoder: AudioEncoder.flac,
    bitRate: 320000,
    numChannels: 1,
  ),
  path: filePath,
);
```

**Additional context**

```
D/CCodec  ( 5748): allocate(c2.android.flac.encoder)
I/Codec2Client( 5748): Available Codec2 services: "default" "default1" "default2" "software"
I/CCodec  ( 5748): setting up 'default' as default (vendor) store
I/CCodec  ( 5748): Created component [c2.android.flac.encoder]
D/CCodecConfig( 5748): read media type: audio/flac
D/ReflectedParamUpdater( 5748): extent() != 1 for single value type: algo.buffers.max-count.values
D/ReflectedParamUpdater( 5748): extent() != 1 for single value type: output.subscribed-indices.values
D/ReflectedParamUpdater( 5748): extent() != 1 for single value type: input.buffers.allocator-ids.values
D/ReflectedParamUpdater( 5748): extent() != 1 for single value type: output.buffers.allocator-ids.values
D/ReflectedParamUpdater( 5748): extent() != 1 for single value type: algo.buffers.allocator-ids.values
D/ReflectedParamUpdater( 5748): extent() != 1 for single value type: output.buffers.pool-ids.values
D/ReflectedParamUpdater( 5748): extent() != 1 for single value type: algo.buffers.pool-ids.values
I/CCodecConfig( 5748): query failed after returning 9 values (BAD_INDEX)
D/CCodecConfig( 5748): c2 config diff is Dict {
D/CCodecConfig( 5748):   c2::u32 algo.complexity.value = 5
D/CCodecConfig( 5748):   c2::u32 coded.bitrate.value = 768000
D/CCodecConfig( 5748):   c2::u32 input.buffers.max-size.value = 4608
D/CCodecConfig( 5748):   c2::u32 input.delay.value = 0
D/CCodecConfig( 5748):   string input.media-type.value = "audio/raw"
D/CCodecConfig( 5748):   string output.media-type.value = "audio/flac"
D/CCodecConfig( 5748):   c2::u32 raw.channel-count.value = 1
D/CCodecConfig( 5748):   c2::u32 raw.pcm-encoding.value = 0
D/CCodecConfig( 5748):   c2::u32 raw.sample-rate.value = 44100
D/CCodecConfig( 5748): }
D/CompatibilityChangeReporter( 5748): Compat change id reported: 263076149; UID 10603; state: ENABLED
I/MediaCodec( 5748): MediaCodec will operate in async mode
D/CodecSeeding( 5748): Seed: codec c2.android.flac.encoder, mediatype audio/flac, overrideable 1
D/CodecProperties( 5748): setFeatureValue(_vq_eligible.device,1)
D/CodecProperties( 5748): setFeatureValue(_quality.target,1)
D/CodecSeeding( 5748): Seed: codec c2.android.flac.encoder, mediatype audio/flac, overrideable 0
D/MediaCodec( 5748): shapeMediaFormat: deltas(0): AMessage(what = 0x00000000) = {
D/MediaCodec( 5748):   }
D/CCodec  ( 5748): [c2.android.flac.encoder] buffers are bound to CCodec for this session
D/CCodecConfig( 5748): no c2 equivalents for flags
D/CCodecConfig( 5748): no c2 equivalents for encoder
D/CCodecConfig( 5748): c2 config diff is   c2::u32 algo.complexity.value = 8
D/CCodecConfig( 5748):   c2::u32 coded.bitrate.value = 0
W/Codec2Client( 5748): query -- param skipped: index = 1107298332.
D/CCodec  ( 5748): encoding statistics level = 0
D/CCodec  ( 5748): setup formats input: AMessage(what = 0x00000000) = {
D/CCodec  ( 5748):   int32_t android._codec-pcm-encoding = 2
D/CCodec  ( 5748):   int32_t channel-count = 1
D/CCodec  ( 5748):   int32_t flac-compression-level = 8
D/CCodec  ( 5748):   int32_t max-input-size = 4608
D/CCodec  ( 5748):   string mime = "audio/raw"
D/CCodec  ( 5748):   int32_t pcm-encoding = 2
D/CCodec  ( 5748):   int32_t sample-rate = 44100
D/CCodec  ( 5748):   int32_t android._config-pcm-encoding = 2
D/CCodec  ( 5748): }
D/CCodec  ( 5748): setup formats output: AMessage(what = 0x00000000) = {
D/CCodec  ( 5748):   int32_t android._codec-pcm-encoding = 2
D/CCodec  ( 5748):   int32_t bitrate = 0
D/CCodec  ( 5748):   int32_t channel-count = 1
D/CCodec  ( 5748):   int32_t flac-compression-level = 8
D/CCodec  ( 5748):   int32_t max-bitrate = 0
D/CCodec  ( 5748):   string mime = "audio/flac"
D/CCodec  ( 5748):   int32_t pcm-encoding = 2
D/CCodec  ( 5748):   int32_t sample-rate = 44100
D/CCodec  ( 5748): }
I/CCodecConfig( 5748): query failed after returning 9 values (BAD_INDEX)
D/MediaCodec( 5748): keep callback message for reclaim
W/Codec2Client( 5748): query -- param skipped: index = 1342179345.
W/Codec2Client( 5748): query -- param skipped: index = 2415921170.
W/Codec2Client( 5748): query -- param skipped: index = 3254792206.
D/C2Store ( 5748): debug.c2.use_dmabufheaps set, forcing DMABUF Heaps
D/C2Store ( 5748): Using DMABUF Heaps
D/CCodecBufferChannel( 5748): [c2.android.flac.encoder#308] Created input block pool with allocatorID 16 => poolID 17 - OK (0)
I/CCodecBufferChannel( 5748): [c2.android.flac.encoder#308] Created output block pool with allocatorID 16 => poolID 613 - OK
D/CCodecBufferChannel( 5748): [c2.android.flac.encoder#308] Configured output block pool ids 613 => OK
I/DMABUFHEAPS( 5748): Using DMA-BUF heap named: system
D/CCodecBufferChannel( 5748): [c2.android.flac.encoder#308] MediaCodec discarded an unknown buffer
D/CCodecBufferChannel( 5748): [c2.android.flac.encoder#308] MediaCodec discarded an unknown buffer
D/CCodecBufferChannel( 5748): [c2.android.flac.encoder#308] MediaCodec discarded an unknown buffer
D/CCodecBufferChannel( 5748): [c2.android.flac.encoder#308] MediaCodec discarded an unknown buffer
E/AndroidRuntime( 5748): FATAL EXCEPTION: MediaCodecEncoder Thread
E/AndroidRuntime( 5748): Process: it.klyta.szukadlo, PID: 5748
E/AndroidRuntime( 5748): kotlin.UninitializedPropertyAccessException: lateinit property mContainer has not been initialized
E/AndroidRuntime( 5748):        at com.llfbandit.record.record.encoder.MediaCodecEncoder.stopAndRelease(MediaCodecEncoder.kt:181)
E/AndroidRuntime( 5748):        at com.llfbandit.record.record.encoder.MediaCodecEncoder.onError(MediaCodecEncoder.kt:163)
E/AndroidRuntime( 5748):        at com.llfbandit.record.record.encoder.MediaCodecEncoder.initEncoding(MediaCodecEncoder.kt:103)
E/AndroidRuntime( 5748):        at com.llfbandit.record.record.encoder.MediaCodecEncoder.handleMessage(MediaCodecEncoder.kt:75)
E/AndroidRuntime( 5748):        at android.os.Handler.dispatchMessage(Handler.java:103)
E/AndroidRuntime( 5748):        at android.os.Looper.loopOnce(Looper.java:232)
E/AndroidRuntime( 5748):        at android.os.Looper.loop(Looper.java:317)
E/AndroidRuntime( 5748):        at android.os.HandlerThread.run(HandlerThread.java:85)
I/hw-BpHwBinder( 5748): onLastStrongRef automatically unlinking death recipients
```

**Comment by gonuit** [comment]
Found this. An error is reported when filePath directs to a directory that does not exist. 
I think that this should be somehow handled.

**Comment by llfbandit** [comment]
The raised exception should be fixed with 7508e54f70444a126d400eebdadc3a939f6a841f
Note: the package has will never check if the folder is writable, create needed subfolders, ...

**Comment by gonuit** [comment]
It's not about creating a directory, it is about proper error handling. It should not crash instead a proper error should be returned.

**Comment by llfbandit** [comment]
As stated, it will with next version.
