### ISSUE TITLE
 Failed to handle method call

### ISSUE THREAD

**Issue by sp-sivaprasad** [llfbandit/record#43]
E/MethodChannel#com.llfbandit.record(29081): Failed to handle method call
E/MethodChannel#com.llfbandit.record(29081): java.lang.RuntimeException: setAudioSource failed.
E/MethodChannel#com.llfbandit.record(29081): 	at android.media.MediaRecorder.setAudioSource(Native Method)
E/MethodChannel#com.llfbandit.record(29081): 	at com.llfbandit.record.Recorder.start(Recorder.java:41)
E/MethodChannel#com.llfbandit.record(29081): 	at com.llfbandit.record.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:54)
E/MethodChannel#com.llfbandit.record(29081): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#com.llfbandit.record(29081): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:178)
E/MethodChannel#com.llfbandit.record(29081): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0$DartMessenger(DartMessenger.java:206)
E/MethodChannel#com.llfbandit.record(29081): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$6ZD1MYkhaLxyPjtoFDxe45u43DI.run(Unknown Source:12)
E/MethodChannel#com.llfbandit.record(29081): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#com.llfbandit.record(29081): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#com.llfbandit.record(29081): 	at android.os.Looper.loop(Looper.java:236)
E/MethodChannel#com.llfbandit.record(29081): 	at android.app.ActivityThread.main(ActivityThread.java:8037)
E/MethodChannel#com.llfbandit.record(29081): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#com.llfbandit.record(29081): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
E/MethodChannel#com.llfbandit.record(29081): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by mhstoller** [comment]
Please provide the code you are using to invoke and start the recorder
