### ISSUE TITLE
MissingPluginException(No implementation found for method cancel on channel com.llfbandit.record/eventsRecord/recordId

### ISSUE THREAD

**Issue by gaochang1993** [llfbandit/record#447]
**Package version**
  flutter: 3.24
  record: ^5.2.0

**Environment**
 - OS: Android
 - Flutter: Flutter (Channel stable, 3.24.4, on macOS 15.0.1 24A348 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.24.4 on channel stable at /Users/gaochang/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (6 weeks ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3
    • Pub download mirror https://mirrors.tuna.tsinghua.edu.cn/dart-pub
    • Flutter download mirror https://storage.flutter-io.cn

**Describe the bug**
MissingPluginException(No implementation found for method cancel on channel com.llfbandit.record/eventsRecord/3dc7542f-8ecf-4caf

RecordConfig(
        sampleRate: sampleRate,
        numChannels: 1,
        bitRate: sampleRate,
        echoCancel: true,
        noiseSuppress: true,
        autoGain: true,
        encoder: AudioEncoder.pcm16bits,
        androidConfig: const AndroidRecordConfig(
          audioSource: AndroidAudioSource.voiceCommunication,
        ),
      )

**To Reproduce**

1. recrod.startStream()
2. Just say something
3. Close the page and dipose record
4. Errors occur

**Additional context**

log:
I/flutter (11458): 12/04 13:18:08:509   DEBUG 🐛 <media> dispose media
I/flutter (11458): 12/04 13:18:08:510    INFO 💡 <RealTimeWSMixin> disConnect
D/AudioTrack(11458): stop(983): 0xb400007dd1f80200, prior state:STATE_ACTIVE
D/AudioTrackShared(11458): this(0xb400007f475fd960), mCblk(0x7f47378000), front(0), mIsOut 1, interrupt() FUTEX_WAKE
D/AudioTrack(11458): stop(983): 0xb400007dd1f80200 stop done
D/AudioTrack(11458): stop(983): 0xb400007dd1f80200, prior state:STATE_STOPPED
D/AudioTrack(11458): ~AudioTrack(983): 0xb400007dd1f80200
D/AudioTrack(11458): stop(983): 0xb400007dd1f80200, prior state:STATE_STOPPED
[sentry] [debug] Capture from onError MissingPluginException(No implementation found for method cancel on channel com.llfbandit.record/eventsRecord/3dc7542f-8ecf-4caf-b6dc-8dd5f94ef515)
[sentry.flutterError] [error] Exception caught by services library
                      MissingPluginException(No implementation found for method cancel on channel com.llfbandit.record/eventsRecord/3dc7542f-8ecf-4caf...
                      #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
                      <asynchronous suspension>
                      #1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:688:9)
                      <asynchronous suspension>

**Comment by llfbandit** [comment]
Thanks for reporting, I was unable to reproduce this.
Be sure to have your transitive dependencies up to date.

**Comment by Duzilin1994** [comment]
same error

**Comment by B-Saeid** [comment]
> Thanks for reporting, I was unable to reproduce this. Be sure to have your transitive dependencies up to date.

Encountered the same error multiple times either on emulators or physical devices ranging from android 6 to 14.

The point that it is not persistent i.e. it occurs a few times in a while. Here is how it occurred:

CODE:

```
    ...
    final wasNull = _recorder == null;
    await _amplitudeSub?.cancel();
    await _recorder?.cancel();
    await _recorder?.dispose();
    _recorder = null;
    if (!wasNull) print('===================== Disposed Recorder =====================');
    _disposing = false;
    print('=================== sat _disposing to FALSE =====================\n');
}
```


OUTPUT:
```
I/flutter (16225): ===================== Disposed Recorder =====================
I/flutter (16225): =================== sat _disposing to FALSE =====================

======== Exception caught by services library ======================================================
The following MissingPluginException was thrown while de-activating platform stream on channel com.llfbandit.record/eventsRecord/67721118-fccd-41b8-b064-ea98a2db5959:
MissingPluginException(No implementation found for method cancel on channel com.llfbandit.record/eventsRecord/67721118-fccd-41b8-b064-ea98a2db5959)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:688:9)
<asynchronous suspension>
THEN OTHER UNRELATED LOGS 
```

Note: The exception is caught after the call to `await _recorder?.cancel();` hence I am using `await` and print statements to ensure.

This is my config:

```
  _recorder = AudioRecorder();
  _recorder!.startStream(
        RecordConfig(
          encoder: AudioEncoder.pcm16bits,
        ),
      );

```

using record: 5.2.0

**Comment by B-Saeid** [comment]
I manage to suppress this exception by having a singleton recorder instance that is never disposed during app session and be sufficient with calling `cancel`.

Every things worked nicely except for the permanent instance which ,I assume, is far from being called a memory leak as long as it is not used.

```
    ...
    // final wasNull = _recorder == null;
    // await _amplitudeSub?.cancel();
    await _recorder?.cancel();
    // await _recorder?.dispose();
    // _recorder = null;
    // if (!wasNull) print('===================== Disposed Recorder =====================');
    // _disposing = false; // Not need for that at all now as of v 5.1.3 `_safeCall` is used with a `semaphore` GREAT WORK
    // print('=================== sat _disposing to FALSE =====================\n');
}
```

Results in one liner:

```
await _recorder?.cancel();
```

**Comment by llfbandit** [comment]
Thanks for not giving up. I was able to reproduce it. Don't know why I failed before...

**Comment by gaochang1993** [comment]
> reproduce

Cool，thanks very much!
