### ISSUE TITLE
PlatformException caused when stopping recording with a Timer.

### ISSUE THREAD

**Issue by electrooz** [llfbandit/record#46]
I get this when my Timer tries to stop recording. My app is pretty much the example app beside removing the player piece and adding the timers.

The app works with starting/stopping with buttons but the timers make it crash. Any reason why?

```
PlatformException (PlatformException(error, stop failed., null, java.lang.RuntimeException: stop failed.
	at android.media.MediaRecorder.stop(Native Method)
	at com.llfbandit.record.Recorder.stopRecording(Recorder.java:115)
	at com.llfbandit.record.Recorder.stop(Recorder.java:63)
	at com.llfbandit.record.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:62)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(lambda)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5765)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
))
```
This is my added code

```

DateTime startTime = DateTime(2022, 02, 25, 17, 30, 00);
DateTime endTime = DateTime(2022, 02, 25, 17, 32, 00);

```
and I added this first in my build
```
    if (_isRecording == false) {
      Timer(startTime.difference(DateTime.now()), () {
        _start();
        print('START RECORDING');
      });
    }
    if (_isRecording) {
      Timer(endTime.difference(DateTime.now()), () {
        _stop();
        print('END RECORDING');
      });
    }
```

**Comment by llfbandit** [comment]
This because you create a timer each time the widget is rebuilt so `_stop` is called multiple times in the end in a too short period of time.
