### ISSUE TITLE
Platform Exception in iOS

### ISSUE THREAD

**Issue by Harishwarrior** [llfbandit/record#72]
Recording is not working in iOS

Error:

```
"iOS => call release, playerId 2e668bca-614f-4fc2-b2e0-69c771ecf01e"
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: The following exception was thrown Exception from widgets:
flutter: PlatformException(, Failed to start recording, null, null)
flutter: 
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
<asynchronous suspension>
flutter: ----------------------------------------------------
"iOS => call startHeadlessService, playerId b9fd12bc-66a5-48d3-b328-3e1801f9ba76"
"calling start headless service (\n    \"-6035574777829228503\"\n)"
```

**Comment by Harishwarrior** [comment]
Here's my record audio widget

```
class RecordAudioFile extends StatefulWidget {
  const RecordAudioFile({Key? key}) : super(key: key);

  @override
  _RecordAudioFileState createState() => _RecordAudioFileState();
}

class _RecordAudioFileState extends State<RecordAudioFile> {
  ///Record plugins instance for recording audio
  Record record = Record();

  ///Format used for naming the newly recorded audio file
  var formatter = DateFormat('yyyyMMddHHmmss');

  ///Path for storing the recorded audio
  String recordPath = "";

  ///To display the timer in screen
  double seconds = 0.0;

  ///Timer instance for accessing the timer class
  Timer? timer;

  ///To find the recording is running or not
  bool isRecording = false,

      ///To decide the player is need to show or not
      showPlayOption = false;

  @override
  void initState() {
    super.initState();
    getAudioFilePath();
  }

  @override
  void dispose() {
    if (timer != null) {
      timer!.cancel();
    }
    super.dispose();
  }

  ///Function for getting path to store to recorded audio
  Future<void> getAudioFilePath() async {
    if (await record.hasPermission()) {
      String dir = Platform.isIOS
          ? (await getApplicationDocumentsDirectory()).path
          : (await getExternalStorageDirectory())!.path;
      print("the path for audio is $dir");

      String formattedTime = formatter.format(DateTime.now());
      recordPath = dir + "/REC$formattedTime.mp4";

      print("the record path is $recordPath");
    }
  }

  ///Function to get seconds as input and convert it as 00:00 and send back
  String showInTimerFormat(double seconds) {
    int minutes = seconds ~/ 60;

    ///Same as (seconds/60).toInt()
    double remainingSeconds = seconds % 60;
    return '${minutes.toStringAsFixed(0).padLeft(2, '0')} : ${remainingSeconds.toStringAsFixed(0).padLeft(2, '0')}';
  }

  ///Callback function for resetting the audio record screen
  void resetRecordCallBack() {
    if (mounted) {
      setState(() {
        seconds = 0.0;
        showPlayOption = false;
      });
    }
  }

  ///Callback function for popping the screen with sending recorded path
  void saveAudioCallBack() {
    Navigator.pop(context, recordPath);
  }

  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: () async {
        Navigator.pop(context, "");
        return true;
      },
      child: Scaffold(
        appBar: AppBar(
          backgroundColor: Colors.transparent,
          elevation: 0.0,
          leading: IconButton(
            icon: const Icon(Icons.arrow_back_ios),
            onPressed: () {
              Navigator.pop(context, "");
            },
          ),
        ),
        body: SizedBox(
          height: MediaQuery.of(context).size.height,
          width: MediaQuery.of(context).size.width,
          child: Padding(
            padding: const EdgeInsets.only(
              top: 32.0,
              left: 16.0,
              right: 16.0,
            ),
            child: Column(
              children: [
                Text(
                  "Recording time",
                  style: TextStyle(
                    fontSize: 21,
                    color: Theme.of(context)
                        .textTheme
                        .headline1!
                        .color!
                        .withOpacity(0.6),
                  ),
                ),
                const SizedBox(
                  height: 12.0,
                ),
                Text(
                  showInTimerFormat(seconds),
                  style: const TextStyle(
                    fontSize: 40,
                  ),
                ),
                const SizedBox(
                  height: 12.0,
                ),
                GestureDetector(
                  onTap: () {
                    if (mounted) {
                      setState(() {
                        isRecording = !isRecording;
                        showPlayOption = false;
                        if (isRecording) {
                          seconds = 0.0;
                        }
                      });
                    }
                    if (isRecording) {
                      timer =
                          Timer.periodic(const Duration(seconds: 1), (timer) {
                        if (mounted) {
                          setState(() {
                            seconds = seconds + 1;
                          });
                        }
                      });
                      record.start(
                        path: recordPath, // required
                        encoder: AudioEncoder.aacHe,
                      );
                    } else {
                      record.stop();
                      if (timer != null && timer!.isActive) {
                        timer!.cancel();
                      }
                      if (mounted) {
                        setState(() {
                          showPlayOption = true;
                        });
                      }
                    }
                  },
                  child: Container(
                    height: 150.0,
                    width: 150.0,
                    padding: const EdgeInsets.all(defaultPadding * 2),
                    decoration: BoxDecoration(
                      color: Theme.of(context).backgroundColor,
                      borderRadius: BorderRadius.circular(120.0),
                      boxShadow: const [
                        BoxShadow(
                          offset: Offset(2, 2),
                          blurRadius: 10,
                          color: Color.fromRGBO(0, 0, 0, 0.07),
                        ),
                      ],
                    ),
                    child: isRecording
                        ? SvgPicture.asset(
                            'assets/icons/stoprecord.svg',
                            color: kPrimarySeedColor,
                            key: const ValueKey('Record Icon'),
                          )
                        : SvgPicture.asset(
                            'assets/icons/recordaudio.svg',
                            color: kPrimarySeedColor,
                            key: const ValueKey('Record Icon'),
                          ),
                  ),
                ),
                const SizedBox(
                  height: 12.0,
                ),
                Text(
                  isRecording ? "Tap to stop" : "Press the button to record",
                  style: TextStyle(
                    fontSize: 16,
                    color: Theme.of(context)
                        .textTheme
                        .headline1!
                        .color!
                        .withOpacity(0.7),
                  ),
                ),
                if (showPlayOption) ...[
                  Divider(
                    color: Theme.of(context)
                        .textTheme
                        .headline1!
                        .color!
                        .withOpacity(0.4),
                    endIndent: 20,
                    indent: 20,
                  ),
                  const SizedBox(
                    height: 16.0,
                  ),
                  Align(
                      alignment: Alignment.centerLeft,
                      child: Text(
                        "Recording",
                        style: TextStyle(
                          fontSize: 14,
                          color: Theme.of(context)
                              .textTheme
                              .headline1!
                              .color!
                              .withOpacity(0.7),
                        ),
                      )),
                  PlayerWidget(
                    url: recordPath,
                    resetRecordCallBack: resetRecordCallBack,
                    saveAudioCallBack: saveAudioCallBack,
                  ),
                  SizedBox(
                    width: MediaQuery.of(context).size.width,
                    height: 52.0,
                    child: ElevatedButton(
                      onPressed: () {
                        Navigator.pop(context, recordPath);
                      },
                      child: const Text("Add"),
                    ),
                  )
                ],
              ],
            ),
          ),
        ),
      ),
    );
  }
}

```

**Comment by alihuseyin** [comment]
I get the same error on iPhone and iPad emulators.

**Comment by Harishwarrior** [comment]
Temporary workaround: Use an older version of package.

**Comment by Ali-720** [comment]
Hey, I am having the same error. Let me know which version are you using?

**Comment by llfbandit** [comment]
Version 4.2.0-dev.2 should provide error details for iOS.
Please retry with this one.

**Comment by nehal076** [comment]
I am having the same issue on iOS.

`Unhandled Exception: PlatformException(, Failed to start recording, null, null)`

@llfbandit 
How can I fix this?

**Comment by Harishwarrior** [comment]
> I am having the same issue on iOS.
> 
> `Unhandled Exception: PlatformException(, Failed to start recording, null, null)`
> 
> @llfbandit 
> How can I fix this?

Use an older version of package. Currently, that's the only workaround.

**Comment by nehal076** [comment]
Which version? I tried `record: ^4.2.0-dev.2`. Getting the same exception.

**Comment by Harishwarrior** [comment]
> Which version? I tried `record: ^4.2.0-dev.2`. Getting the same exception.

Try ^3.0.2

**Comment by Harishwarrior** [comment]
@llfbandit can you reopen this issue?

**Comment by nehal076** [comment]
@Harishwarrior after changing to 3.0.2

I got this 

```
Could not cast value of type '__NSCFNumber' (0x7fff86cf4b80) to 'NSString' (0x7fff86cf3f70).
Lost connection to device.
Exited
```

The app crashed

**Comment by Harishwarrior** [comment]
> @Harishwarrior after changing to 3.0.2
> 
> I got this 
> 
> ```
> Could not cast value of type '__NSCFNumber' (0x7fff86cf4b80) to 'NSString' (0x7fff86cf3f70).
> Lost connection to device.
> Exited
> ```
> 
> The app crashed

Which flutter version you are using ?

**Comment by nehal076** [comment]
3.0.5

**Comment by Harishwarrior** [comment]
> 3.0.5
> 

I mean which *flutter version*. The latest version of record works fine in Latest version of Flutter.

**Comment by Harishwarrior** [comment]
> @Harishwarrior after changing to 3.0.2
> 
> I got this 
> 
> ```
> Could not cast value of type '__NSCFNumber' (0x7fff86cf4b80) to 'NSString' (0x7fff86cf3f70).
> Lost connection to device.
> Exited
> ```
> 
> The app crashed

Try flutter clean, restart Xcode/ VScode and try again.

**Comment by nehal076** [comment]
<img width="93" alt="image" src="https://user-images.githubusercontent.com/32421196/182017803-fc7224be-3d35-42f4-9a0b-c2dfbd33c0bb.png">
 Flutter Version

**Comment by Harishwarrior** [comment]
> <img width="545" alt="image" src="https://user-images.githubusercontent.com/32421196/182017837-ead16b6b-2c29-46ef-b237-87578fa74b9e.png">
>  Flutter Version

@llfbandit seems like the issue isn't fixed. Can you verify this?

**Comment by llfbandit** [comment]
Please try with latest version 4.3.2. Additional info message should be provided on this exception from version 4.3.0.
I can't do anything myself as I don't reproduce it on my side.

**Comment by Harishwarrior** [comment]
> Please try with latest version 4.3.2. Additional info message should be provided on this exception from version 4.3.0.
> I can't do anything myself as I don't reproduce it on my side.

Thanks for the package.

**Comment by sejun2** [comment]
In my case, it was a problem of file extension. First, I save my file as .wav that makes error with such exception. But after change file extension to .m4a, then it works fine now.

Hope it helpful

**Comment by Harishwarrior** [comment]
> Please try with latest version 4.3.2. Additional info message should be provided on this exception from version 4.3.0. I can't do anything myself as I don't reproduce it on my side.

2022-10-13 15:58:55.620510+0300 Runner[2682:83639] flutter: ----------------FIREBASE CRASHLYTICS----------------
2022-10-13 15:58:55.620635+0300 Runner[2682:83639] flutter: PlatformException(-1, Failed to start recording, Error Domain=NSOSStatusErrorDomain Code=1718449215 "(null)", null)
2022-10-13 15:58:55.620727+0300 Runner[2682:83639] flutter: 
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
<asynchronous suspension>
2022-10-13 15:58:55.620767+0300 Runner[2682:83639] flutter: ----------------------------------------------------
2022-10-13 15:59:02.168106+0300 Runner[2682:83639] flutter: Stop recording
"iOS => call startHeadlessService, playerId 23235a3f-ed22-411e-8b56-19c78ab71363"
"calling start headless service (\n    \"-6035574777829228503\"\n)"

**Comment by baptistesx** [comment]
Hi,

I've had the same error, on an Iphone 7, iOS 15.7.6, after some tries it suddently worked, i haven't done anything special:

![image](https://github.com/llfbandit/record/assets/9638281/96d2d2dd-ab0a-4b20-912c-fa0a8ce0486b)

![image](https://github.com/llfbandit/record/assets/9638281/31f2b6d5-b489-4aae-8dde-e321e216f612)

I'm using Flutter 3.7.12 and record 4.4.4

Do you still recommend to use an older version of the package ? Which one ? 4.3.2?

**Comment by madilsharief** [comment]
Hi, I am facing the same issue same error.

iOS: !6.6
IPhone: XR
Flutter: 3.10.6
Xcode:14.3.1

Can't record at all

**Comment by LeGoffMael** [comment]
> 

Thank you! This way solved my issue.

**Comment by LeGoffMael** [comment]
> In my case, it was a problem of file extension. First, I save my file as .wav that makes error with such exception. But after change file extension to .m4a, then it works fine now.
> 
> Hope it helpful

Thank you! This way solved my issue.
